org.gradle.jvmargs=-Xmx3G
mod_id=runepouch
mod_version=1.0.0
mod_group_id=com.example.runepouch
mod_authors=Termux_Dev
mod_description=A pouch to carry all your runes. Holds 18 runes (9x2).
mod_credits=Termux_Dev
mod_homepage=https://github.com/peterbc231/rune-pouch-mod
mod_display_url=https://github.com/peterbc231/rune-pouch-mod
mod_update_url=
minecraft_version=1.16.5
forge_version=36.2.42
loader_version=36.2.42
minecraft_version_range=[1.16.5,1.17)
forge_version_range=[36.0.0,37.0.0)
loader_version_range=[36.0.0,37.0.0)
mapping_channel=stable
mapping_version=46-1.16.5
mod_display_name=Rune Pouch
mod_logo_file=
mod_issue_tracker_url=
