modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="runepouch"
version="1.0.0"
displayName="Rune Pouch"
authors="741741"
description="A pouch for carrying runes. Supports Curios API."

[[dependencies.runepouch]]
modId="curios"
mandatory=true
versionRange="*"
ordering="AFTER"
side="BOTH"

[[dependencies.runepouch]]
modId="aoa3"
mandatory=true
versionRange="*"
ordering="AFTER"
side="BOTH"

[[dependencies.runepouch]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.runepouch]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
